import type { LangiumSharedCoreServices } from 'langium';
import { inject, Module } from 'langium';
import { KernoGeneratedModule, KernoGeneratedSharedModule } from './generated/module.js';
import { KernoSemanticTokenization } from './lsp/kerno-semantic-tokenization.js';
import { KernoScopeProvider } from './lsp/kerno-scope-provider.js';
import { KernoCompletionProvider } from './lsp/kerno-completion-provider.js';
import { KernoScopeComputation } from './lsp/kerno-scope-computation.js';
import { createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, PartialLangiumServices } from 'langium/lsp';
import { KernoDocumentationProvider } from './lsp/kerno-documentation-provider.js';
import { KernoCodeActionProvider } from './lsp/kerno-code-action-provider.js';
import { createLangiumModuleForTypirBinding, initializeLangiumTypirServices, LangiumServicesForTypirBinding } from 'typir-langium';
import { createKernoTypirModule } from './kerno-typir.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type KernoAddedServices = {
    typir: LangiumServicesForTypirBinding,
    validation: {
        // KernoValidator: KernoValidator,
        // KernoAcceptWeaver: KernoAcceptWeaver
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type KernoServices = LangiumServices & KernoAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export function createKernoModule(shared: LangiumSharedCoreServices): Module<KernoServices, PartialLangiumServices & KernoAddedServices> {
    return {
        typir: () => inject(Module.merge(
            createLangiumModuleForTypirBinding(shared), // the Typir default services
            createKernoTypirModule(shared), // custom Typir services for Kerno
        )),
        lsp: {
            SemanticTokenProvider: (services) => new KernoSemanticTokenization(services),
            CompletionProvider: (services) => new KernoCompletionProvider(services),
            CodeActionProvider: (services) => new KernoCodeActionProvider(services)
        },
        references: {
            ScopeProvider: (services) => new KernoScopeProvider(services),
            ScopeComputation: (services) => new KernoScopeComputation(services)
        },
        validation: {
            // KernoValidator: () => new KernoValidator(),
            // KernoAcceptWeaver: () => new KernoAcceptWeaver()
        },
        documentation: {
            DocumentationProvider: (services) => new KernoDocumentationProvider(services)
        }
    };
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function KernoServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Kerno: KernoServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        KernoGeneratedSharedModule
    );
    const Kerno = inject(
        createDefaultModule({ shared }),
        KernoGeneratedModule,
        createKernoModule(shared)
    );
    shared.ServiceRegistry.register(Kerno);
    // registerValidationChecks(Kerno);
    // weaveAcceptMethods(Kerno);
    initializeLangiumTypirServices(Kerno, Kerno.typir);
    return { shared, Kerno: Kerno };
}
